# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Francesco Levorato
tagline:          'Enthusiast.'
description:      'Revolutioning integrations one background task at a time.'
url:              https://flevour.net
baseurl:          /

author:
  name:           'Francesco Levorato'
  url:            https://twitter.com/flevour

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/flevour/flevour.github.io
